### ISSUE TITLE
How to install to iOS

### ISSUE THREAD

**Issue by noymer** [quipper/react-native-td#12]
I have tried to install `react-native-td`, but build is failed.
The failed repo is https://github.com/noymer/RNTreasureDataExample
How to install it?

## questions

1. Isn't `pod install` is necessary?

2. Could you write down installation process, like 

```
yarn add react-native-td
react-native link react-native-td
cd ios
pod init
...
```

3. Where is the mistake in my procedure `how I did` below?

---

## how I did

Below is how I did in [the repo](https://github.com/noymer/RNTreasureDataExample).

``` bash
$ react-native -v
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
$ react-native init RNTreasureDataExample --version react-native@0.52.2
$ cd RNTreasureDataExample

$ yarn add react-native-td
$ react-native link react-native-td
$ pod init

# edit podfile
vim ios/Podfile 
```

In this timing code is: https://github.com/noymer/RNTreasureDataExample/commit/088b74848840a68bf3826c82798d3b1f419322c3
And build was failed.

```
$ ./node_modules/.bin/react-native run-ios

...
{...}/RNTreasureDataExample/node_modules/react-native-td/ios/RNTreasureData.m:3:9: fatal error: 'TreasureData-iOS-SDK/TreasureData.h' file not found
#import <TreasureData-iOS-SDK/TreasureData.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.



** BUILD FAILED **



The following build commands failed:
    CompileC {...}/RNTreasureDataExample/ios/build/Build/Intermediates.noindex/RNTreasureData.build/Debug-iphonesimulator/RNTreasureData.build/Objects-normal/x86_64/RNTreasureData.o RNTreasureData.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/RNTreasureDataExample.app
Launching org.reactjs.native.example.RNTreasureDataExample
org.reactjs.native.example.RNTreasureDataExample: 99610
```

I tried `pod install`

``` bash
$ cd ios
$ pod install
```

In this timing code is: https://github.com/noymer/RNTreasureDataExample/commit/af86d97845a33db79f3fd432f742ccb70589440c
But build failed again.

```
$ cd ../
$  ./node_modules/.bin/react-native run-ios

...

** BUILD FAILED **



The following build commands failed:
    CompileC {...}/RNTreasureDataExample/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTDevSettings.o {...}/RNTreasureDataExample/node_modules/react-native/React/Modules/RCTDevSettings.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/RNTreasureDataExample.app
Launching org.reactjs.native.example.RNTreasureDataExample
org.reactjs.native.example.RNTreasureDataExample: 518
```

When I opened the workspace in xcode and tried to build, failed again.

![image](https://user-images.githubusercontent.com/8816130/35549864-fdac3962-05ca-11e8-9050-36ead7c1da12.png)

**Comment by hotchemi** [comment]
@noymer Thx for your dedicated info! We'll check your example later and could you possibly check the following points?

- Does the sample work on Android?
- Can you try to re-install dependencies as the following order?
  -  yarn add react-native-td
  - cd ios
  - pod init
  - (edit podfile)
  - pod install
  - react-native link react-native-td

**Comment by noymer** [comment]
@hotchemi Thank you quick response! 

On Android, the sample works.
(except DuplicateFileException, but it doesn't matter)

I will try re-install.

**Comment by noymer** [comment]
>Can you try to re-install dependencies as the following order?
yarn add react-native-td
cd ios
pod init
(edit podfile)
pod install
react-native link react-native-td

Unfortunatelly, even if I re-installed,
build is failed with the same error. 

The re-installed code is:
https://github.com/noymer/RNTreasureDataExample/tree/d0b0903901716bdaa942cb0b4e8e8cae3167a3ab

**Comment by noymer** [comment]
Hi,

After some searching, I found this issue.
https://github.com/facebook/react-native/issues/17799

I modified code [like this,](https://github.com/noymer/RNTreasureDataExample/blob/485c49b31f579f7bf1b8b315d12ac32e2df3c914/ios/Podfile#L10-L12)
```
pod 'React', path: '../node_modules/react-native', subspecs: [
    'DevSupport'
    ]
```

and both android and iOS builds succeeded!

The build suceeded code is:
https://github.com/noymer/RNTreasureDataExample/tree/485c49b31f579f7bf1b8b315d12ac32e2df3c914

**Comment by hotchemi** [comment]
@noymer Ooh thx for the investigation 🙇 
I'd say we should modify example code and readme like below to align RN official guide 🙇
Thank you for your dedicated work~!

```ruby
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
```

**Comment by hotchemi** [comment]
Addressed, thx guys!
